[book]
title = "Design and Analysis of Algorithms"
authors = ["Suvabrata Chowdhury"]
language = "en"

[output.html]
git-repository-url = "https://github.com/SuvabrataChowdhury/Algorithm_Notes"
mathjax-support = false
smart-punctuation = false
theme = "src/theme"
